# Generated by Django 3.2.6 on 2022-04-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobel_User_Name', models.CharField(blank=True, max_length=256, null=True)),
                ('Mobel_Email_Address', models.CharField(blank=True, max_length=256, null=True)),
                ('Mobel_Password', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'User Information',
            },
        ),
    ]
